package re.clet.pebblestrava

import java.util.UUID

object Constants {
    val APP_UUID: UUID = UUID.fromString("2d64ac7d-a175-4bb0-ba11-8c1997cff52d")

    // AppMessage key values — auto-generated by Pebble SDK from package.json messageKeys (base 10000)
    const val KEY_CMD_ACTION    = 10000
    const val KEY_CMD_SPORT     = 10001
    const val KEY_HR_BPM        = 10002
    const val KEY_GPS_DISTANCE  = 10003
    const val KEY_GPS_SPEED     = 10004
    const val KEY_GPS_HAS_FIX   = 10005
    const val KEY_UPLOAD_STATUS = 10006
    const val KEY_UPLOAD_MSG    = 10007
    const val KEY_CRED_REQUEST  = 10008
    const val KEY_CRED_URL      = 10009
    const val KEY_CRED_SECRET   = 10010
    const val KEY_WORKER_STATUS                = 10011
    const val KEY_SETTINGS_HR_INTERVAL_CYCLING = 10012
    const val KEY_SETTINGS_HR_INTERVAL_RUNNING = 10013
    const val KEY_SETTINGS_HR_INTERVAL_WALKING = 10014
    const val KEY_SETTINGS_GPS_ACCURACY        = 10015
    const val KEY_SETTINGS_UNITS               = 10016

    // CMD_ACTION values
    const val CMD_START  = 0
    const val CMD_STOP   = 1
    const val CMD_PAUSE  = 2
    const val CMD_RESUME = 3

    // CMD_SPORT values (order must match the watch C defines)
    const val SPORT_CYCLING = 0
    const val SPORT_RUNNING = 1
    const val SPORT_WALKING = 2

    // UPLOAD_STATUS values
    const val UPLOAD_PENDING = 0
    const val UPLOAD_SUCCESS = 1
    const val UPLOAD_ERROR   = 2

    // WORKER_STATUS values
    const val WORKER_OK    = 1
    const val WORKER_ERROR = 2

    const val PREFS_NAME              = "pebble_strava_prefs"
    const val PREF_WORKER_URL         = "worker_url"
    const val PREF_WORKER_SECRET      = "worker_secret"
    const val PREF_LAST_GPS_TIME      = "last_gps_time"
    const val PREF_LAST_GPS_ACC       = "last_gps_acc"
    const val PREF_LAST_APP_OPENED    = "last_app_opened_ms"   // epoch ms, 0 = never seen
    const val PREF_GPS_ACCURACY       = "gps_accuracy"         // 15 / 25 / 50 m
    const val PREF_UNITS              = "units"                 // 0 = metric, 1 = imperial

    const val NOTIF_CHANNEL_ID = "gps_tracking"
    const val NOTIF_ID         = 1

    // GPS send throttle — send distance/speed to watch every N active fixes (~5 s at 1 s GPS rate)
    const val GPS_SEND_EVERY = 5
}
